---
- name: Install Qemu
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - python3-lxml
    update_cache: yes
    state: present
- name: Ensure libvirtd service is started and enabled
  ansible.builtin.systemd_service:
    name: libvirtd
    state: started
    enabled: yes
- name: Add the user to the libvirt group
  ansible.builtin.user:
    name: "ubuntu"
    groups: libvirt
    append: yes
- name: Add the user to the kvm group
  ansible.builtin.user:
    name: "ubuntu"
    groups: kvm
    append: yes
- name: Ensure pool directory exists
  file:
    path: "{{ pool_path }}"
    state: directory
    mode: "0755"
- name: Ensure storage pool bigpool is present, active and autostart
  community.libvirt.virt_pool:
    name: "{{ pool_name }}"
    state: present
    xml: "{{ lookup('template', 'pool.xml.j2') }}"
