---
- name: hostunlimited setup
  hosts: hostunlimited
  become: true

  vars_files: vars/basics.yml

  vars:
    certbot_certs:
      - domains:
        - "hostunlimited.paperbenni.xyz"

  pre_tasks:
    - name: ensure apt cache is updated
      apt: update_cache=true cache_valid_time=3600
    - name: ensure paperbenni user exists
      user:
        name: paperbenni
        state: present
        groups: sudo
        append: yes
    - name: Ensure ssh key is authorized
      authorized_key:
        user: paperbenni
        state: present
        key: "{{ lookup('file', '/home/benjamin/.ssh/id_rsa.pub') }}"


  roles:
    - grog.sudo
    - geerlingguy.pip
    - geerlingguy.certbot
    - geerlingguy.security
    - geerlingguy.nginx
    - geerlingguy.docker
    - robertdebock.cargo

  tasks:
    - name: Ensure docroot exists
      file:
        path: "{{ nginx_docroot }}"
        state: directory
    - name: copy nginx server config
      template:
        src: templates/https-letsencrypt.conf.j2
        dest: /etc/nginx/sites-enabled/https-letsencrypt.conf
        mode: 0644
      notify: restart nginx
  
  handlers:
    - import_tasks: handlers/basics.yml
