---
- name: oracle 2 setup
  hosts: oracle2
  become: yes

  vars:
    certbot_certs:
      - domains:
          - "packages.instantos.io"
          - "minecraft.paperbenni.xyz"
    mpm_dir: ~/workspace/mpm-repo
    minecraft_version: "1.20"
    firewall_allowed_tcp_ports:
      - "22"
      - "25"
      - "80"
      - "443"
      - "25565"
      - "7777"
      - "42695"
      - "3000"
      - "64738"
      - "8008"
      - "9005"
      - "19132"
      - "8000"
      - "8443"
    firewall_allowed_udp_ports:
      - "64738"
      - "25565"
      - "19132"
    firewall_flush_rules_and_chains: true

  vars_files:
    - vars/basics.yml
    - secrets.yml

  pre_tasks:
    - name: ensure apt cache is updated
      apt: update_cache=true cache_valid_time=3600
    - name: ensure paperbenni user exists
      user:
        name: paperbenni
        state: present
        groups: sudo
        append: yes
    - name: Ensure ssh key is authorized
      authorized_key:
        user: paperbenni
        state: present
        key: "{{ lookup('file', '/home/benjamin/.ssh/id_rsa.pub') }}"

  roles:
    - grog.sudo
    - geerlingguy.pip
    - geerlingguy.firewall
    - geerlingguy.certbot
    # - robertdebock.cargo
    - geerlingguy.security
    - geerlingguy.nginx
    - geerlingguy.docker
    - matterbridge
    - mumble
    # - spigot
    - instantosmirror

  tasks:

  handlers:
    - import_tasks: handlers/basics.yml
