---
- name: oracle 1 setup
  hosts: oracle1
  become: yes

  vars:
    certbot_certs:
      - domains:
        - "minecraft.paperbenni.xyz"

  vars_files: vars/basics.yml

  pre_tasks:
    - name: ensure apt cache is updated
      apt: update_cache=true cache_valid_time=3600
    - name: ensure paperbenni user exists
      user:
        name: paperbenni
        state: present
        groups: sudo
        append: yes
    - name: Ensure ssh key is authorized
      authorized_key:
        user: paperbenni
        state: present
        key: "{{ lookup('file', '/home/benjamin/.ssh/id_rsa.pub') }}"

  roles:
    - grog.sudo
    - geerlingguy.pip
    - geerlingguy.certbot
    - geerlingguy.security
    - geerlingguy.nginx
    - geerlingguy.docker_arm
    - robertdebock.cargo


  tasks:
    - name: Ensure docroot exists
      file:
        path: "{{ nginx_docroot }}"
        state: directory

  handlers:
    - import_tasks: handlers/basics.yml
