---
- name: oracle 2 setup
  hosts: oracle2
  become: yes

  vars:
    certbot_certs:
      - domains:
          - "minecraft.paperbenni.xyz"
    mpm_dir: ~/workspace/mpm-repo
    minecraft_version: "1.18"

  vars_files: vars/basics.yml

  pre_tasks:
    - name: ensure apt cache is updated
      apt: update_cache=true cache_valid_time=3600
    - name: ensure paperbenni user exists
      user:
        name: paperbenni
        state: present
        groups: sudo
        append: yes
    - name: Ensure ssh key is authorized
      authorized_key:
        user: paperbenni
        state: present
        key: "{{ lookup('file', '/home/benjamin/.ssh/id_rsa.pub') }}"

  roles:
    - grog.sudo
    - geerlingguy.pip
    - geerlingguy.certbot
    - robertdebock.cargo
    - geerlingguy.security
    - geerlingguy.nginx
    - geerlingguy.docker_arm

  tasks:
    - name: Ensure docroot exists
      file:
        path: "{{ nginx_docroot }}"
        state: directory
    - name: ensure mpm is installed
      shell:
        cmd: "curl -Ls https://raw.githubusercontent.com/paperbenni/mpm/master/install.sh | bash"
        creates: /usr/local/bin/mpm
    - name: ensure java is installed
      apt: name=openjdk-17-jre
    - name: ensure extra needed packages are installed
      apt:
        name:
          - neovim
          - tmux
          - wget
          - curl
          - jq
          - zsh
    - name: update spigot
      copy:
        src: "~/workspace/mpm-repo/spigot/{{ minecraft_version }}/spigot.jar"
        dest: /home/ubuntu/spigot/spigot.jar
        owner: ubuntu
        mode: 0755
    - name: update spigot plugins
      copy:
        src: "{{ mpm_dir }}/plugins/{{ item }}/{{ minecraft_version }}/{{ item }}.jar"
        dest: "/home/ubuntu/spigot/plugins/{{ item }}.jar"
        owner: ubuntu
      with_items:
        - chat
        - essentials
        - floodgate
        - geyser
        - griefprevention
        - luckperms
        - slimefun
        - vault
        - viabackwards
        - viarewind
        - viaversion
    - name: ensure systemd user services directory exists
      file:
        name: ~/.config/systemd/user
        state: directory
      become_user: ubuntu
      tags: [spigot]
    - name: install spigot service
      copy:
        src: files/services/spigot.service
        dest: ~/.config/systemd/user/spigot.service
      become_user: ubuntu
      tags: [spigot]
    - name: enable spigot
      systemd:
        scope: user
        state: started
        enabled: yes
        name: spigot.service
      become_user: ubuntu
      tags: [spigot]

  handlers:
    - import_tasks: handlers/basics.yml
