---
roles:
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.pip
    version: 3.1.2
  - name: geerlingguy.ntp
    version: 4.0.0
  - name: geerlingguy.certbot
    version: 5.4.1
  - name: geerlingguy.nginx
    version: 3.3.0
  - name: geerlingguy.security
    version: 3.0.2
  - name: geerlingguy.firewall
    version: 2.7.0
  - name: geerlingguy.swap
    version: 2.0.0
  - name: grog.sudo
    version: v1.7.1
collections:
  - name: ansible.posix
    version: 2.2.0
  - name: community.general
    version: 13.0.1
  - name: community.docker
    version: 5.2.1
  - name: community.libvirt
    version: 2.2.0
