---
roles:
  - name: geerlingguy.docker
    version: 7.1.0
  - name: geerlingguy.pip
    version: 3.0.2
  - name: geerlingguy.ntp
    version: 2.3.3
  - name: geerlingguy.certbot
    version: 5.1.0
  - name: geerlingguy.nginx
    version: 3.1.4
  - name: geerlingguy.security
    version: 2.2.2
  - name: geerlingguy.firewall
    version: 2.5.1
  - name: geerlingguy.swap
    version: 1.2.0
  - name: robertdebock.cargo
    version: 3.1.6
  - name: grog.sudo
    version: v1.7.0


