---
roles:
  - name: geerlingguy.docker_arm
    version: 5.0.0
  - name: geerlingguy.docker
    version: 6.0.4
  - name: geerlingguy.pip
    version: 2.2.0
  - name: geerlingguy.ntp
    version: 2.3.1
  - name: geerlingguy.certbot
    version: 5.0.2
  - name: geerlingguy.nginx
    version: 3.1.4
  - name: geerlingguy.security
    version: 2.2.0
  - name: geerlingguy.firewall
    version: 2.5.1
  - name: robertdebock.cargo
    version: 3.1.2
  - name: grog.sudo
    version: v1.6.0


