---
roles:
  - name: geerlingguy.docker
    version: 7.4.3
  - name: geerlingguy.pip
    version: 3.1.0
  - name: geerlingguy.ntp
    version: 2.6.0
  - name: geerlingguy.certbot
    version: 5.2.1
  - name: geerlingguy.nginx
    version: 3.2.0
  - name: geerlingguy.security
    version: 2.6.0
  - name: geerlingguy.firewall
    version: 2.5.1
  - name: geerlingguy.swap
    version: 1.2.0
  - name: robertdebock.cargo
    version: 3.1.6
  - name: grog.sudo
    version: v1.7.0


