---
- name: Stuff setup
  hosts: stuff
  become: true
  vars_files:
    - vars/basics.yml
    - secrets.yml
  vars:
    swap_file_size_mb: "4096"
    firewall_allowed_tcp_ports:
      - "22" # ssh
      - "25565" # minecraft
      - "80" # http
      - "443" # http
      - "19132" # minecraft bedrock
    firewall_allowed_udp_ports:
      - "25565" # minecraft
      - "19132" # minecraft bedrock
    firewall_flush_rules_and_chains: true
  roles:
    - ubuntu
    - grog.sudo
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.swap
    - geerlingguy.docker
    - caddy
    - { role: litellm, tags: litellm }
    - earlyoom
    - { role: storagebox, tags: storagebox }
  handlers:
    - import_tasks: handlers/basics.yml
