---
- name: Install rsync
  ansible.builtin.apt:
    name:
      - rsync
    state: present
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /data/caddy/file
    - /data/caddy/site
    - /data/caddy/data
    - /data/caddy/config
- name: Create Caddyfile with package configuration
  ansible.builtin.copy:
    dest: /data/caddy/file/Caddyfile
    content: |
      packages.instantos.io {
          root * /srv/
          file_server {
              browse
              precompressed br gzip
          }

          encode gzip
      }
    mode: "0644"
- name: Set up caddy
  community.docker.docker_compose_v2:
    project_name: caddy
    pull: "always"
    definition:
      version: "3.7"
      services:
        caddy:
          image: caddy:latest
          restart: unless-stopped
          network_mode: host # Critical for direct port access
          volumes:
            - /data/caddy/file/Caddyfile:/etc/caddy/Caddyfile
            - /data/caddy/site:/srv
            - /data/caddy/data:/data
            - /data/caddy/config:/config
- name: Ensure all instantOS packages are in caddy
  ansible.builtin.copy:
    src: ~/instantbuild/
    dest: /data/caddy/site/
    mode: "0644"
    directory_mode: "0755"
