---
- name: Install rsync
  ansible.builtin.apt:
    name:
      - rsync
    state: present
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /data/caddy/site
- name: Create instantOS packages Caddy configuration
  ansible.builtin.copy:
    dest: /etc/caddy/conf.d/packages.caddy
    content: |
      packages.instantos.io {
        root * /srv/
        file_server {
          browse
          precompressed br gzip
        }

        encode gzip
      }
    mode: "0644"
  notify: reload caddy
- name: Ensure all instantOS packages are in caddy
  ansible.builtin.copy:
    src: ~/instantbuild/
    dest: /data/caddy/site/
    mode: "0644"
    directory_mode: "0755"
