---
- name: set up caddy
  docker_compose:
    project_name: caddy
    definition:
      version: "3.7"
      services:
        caddy:
          image: caddy:latest
          restart: unless-stopped
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - /data/caddy/file/Caddyfile:/etc/caddy/Caddyfile
            - /data/caddy/site:/srv
            - /data/caddy/data:/data
            - /data/caddy/config:/config
- name: ensure all instantOS packages are in caddy
  copy:
    src: ~/instantbuild/
    dest: /data/caddy/site/
