---
- name: Git checkout botamusique
  git:
    repo: "https://github.com/azlux/botamusique.git"
    dest: /opt/programs/botamusique
    force: yes
    version: 7.2.2
- name: ensure wheel is installed for botamusique
  pip:
    name: wheel
    virtualenv: /opt/programs/botamusique/venv
- name: ensure botamusique dependencies are installed
  pip:
    requirements: /opt/programs/botamusique/requirements.txt
    virtualenv: /opt/programs/botamusique/venv
- name: ensure botamusique config is installed
  copy:
    src: files/config/botamusique_config.ini
    dest: /opt/programs/botamusique/configuration.ini
- name: install botamusique systemd service
  copy:
    src: files/services/botamusique.service
    dest: /etc/systemd/system/botamusique.service
    mode: 0644
- name: Ensure systemd service is enabled
  systemd:
    state: started
    enabled: yes
    name: botamusique
