---
- name: Ensure mumble is set up
  community.docker.docker_compose_v2:
    project_name: mumble
    definition:
      services:
        mumble-server:
          image: mumblevoip/mumble-server:latest
          container_name: mumble-server
          restart: unless-stopped
          environment:
            - "MUMBLE_SUPERUSER_PASSWORD={{ mumble_password }}"
          volumes:
            - "/mnt/backup-server/mumble:/data"
          ports:
            - 64738:64738
            - 64738:64738/udp
