---
- name: Ensure needed packages are installed
  apt:
    name:
      - curl
      - cockpit
      - python3-venv
      - opus-tools
      - nload
      - npm
      - nginx-extras
      - htop
      - jq
      - ffmpeg
      - python3-virtualenv
      - zsh
      - mumble-server
- name: ensure mumble-server has required permissions
  debconf:
    name: mumble-server/use_capabilities
    question: mumble-server/use_capabilities
    value: "true"
    vtype: select
- name: ensure mumble-server autostarts daemon
  debconf:
    name: mumble-server/start_daemon
    question: mumble-server/start_daemon
    value: "true"
    vtype: select
- name: ensure mumble server superuser password is set
  debconf:
    name: mumble-server/password
    question: mumble-server/password
    value: "{{ mumble_password }}"
    vtype: password
  no_log: True
- name: install mumble-server config
  template:
    src: templates/mumble-server.ini.j2
    dest: /etc/mumble-server.ini
    mode: 0644
  notify: restart mumble
- name: ensure opt programs directory exists
  file:
    name: /opt/programs
    state: directory
- name: ensure mumble server is enabled
  systemd:
    state: started
    enabled: yes
    name: mumble-server
