---
- name: ensure matterbridge directory exists
  file:
    name: "/apps/matterbridge"
    state: directory
- name: install matterbridge config
  template:
    src: templates/matterbridge.toml.j2
    dest: "/apps/matterbridge/matterbridge.toml"
    mode: 0644
- name: Ensure matterbridge is set up
  community.docker.docker_compose_v2:
    project_name: matterbridge
    definition:
      services:
        matterbridge:
          image: 42wim/matterbridge:stable
          restart: unless-stopped
          volumes:
          - /apps/matterbridge/matterbridge.toml:/etc/matterbridge/matterbridge.toml:ro
      #    command: -debug
